//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region Metadatos de relaciones en EDM

[assembly: EdmRelationshipAttribute("CineSalinasModel", "FK__cartelera__idCat__1CF15040", "categorias", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(CineSalinas.categorias), "cartelera", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(CineSalinas.cartelera), true)]
[assembly: EdmRelationshipAttribute("CineSalinasModel", "FK__peliculas__idCar__21B6055D", "cartelera", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(CineSalinas.cartelera), "peliculas", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(CineSalinas.peliculas), true)]
[assembly: EdmRelationshipAttribute("CineSalinasModel", "FK__cines__idComuna__145C0A3F", "comunas", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(CineSalinas.comunas), "cines", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(CineSalinas.cines), true)]
[assembly: EdmRelationshipAttribute("CineSalinasModel", "FK__funcion__idCine__286302EC", "cines", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(CineSalinas.cines), "funcion", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(CineSalinas.funcion), true)]
[assembly: EdmRelationshipAttribute("CineSalinasModel", "FK__entrada__idFunci__2C3393D0", "funcion", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(CineSalinas.funcion), "entrada", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(CineSalinas.entrada), true)]
[assembly: EdmRelationshipAttribute("CineSalinasModel", "FK__entrada__usuario__2B3F6F97", "usuarios", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(CineSalinas.usuarios), "entrada", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(CineSalinas.entrada), true)]
[assembly: EdmRelationshipAttribute("CineSalinasModel", "FK__peliculas__idFor__22AA2996", "formatoPeliculas", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(CineSalinas.formatoPeliculas), "peliculas", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(CineSalinas.peliculas), true)]
[assembly: EdmRelationshipAttribute("CineSalinasModel", "FK__funcion__idPelic__276EDEB3", "peliculas", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(CineSalinas.peliculas), "funcion", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(CineSalinas.funcion), true)]
[assembly: EdmRelationshipAttribute("CineSalinasModel", "FK__funcion__idSala__25869641", "salas", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(CineSalinas.salas), "funcion", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(CineSalinas.funcion), true)]
[assembly: EdmRelationshipAttribute("CineSalinasModel", "FK__funcion__idTipoA__267ABA7A", "tipoAsientos", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(CineSalinas.tipoAsientos), "funcion", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(CineSalinas.funcion), true)]

#endregion

namespace CineSalinas
{
    #region Contextos
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    public partial class CineSalinasEntities : ObjectContext
    {
        #region Constructores
    
        /// <summary>
        /// Inicializa un nuevo objeto CineSalinasEntities usando la cadena de conexión encontrada en la sección 'CineSalinasEntities' del archivo de configuración de la aplicación.
        /// </summary>
        public CineSalinasEntities() : base("name=CineSalinasEntities", "CineSalinasEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Inicializar un nuevo objeto CineSalinasEntities.
        /// </summary>
        public CineSalinasEntities(string connectionString) : base(connectionString, "CineSalinasEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Inicializar un nuevo objeto CineSalinasEntities.
        /// </summary>
        public CineSalinasEntities(EntityConnection connection) : base(connection, "CineSalinasEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Métodos parciales
    
        partial void OnContextCreated();
    
        #endregion
    
        #region Propiedades de ObjectSet
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<cartelera> cartelera
        {
            get
            {
                if ((_cartelera == null))
                {
                    _cartelera = base.CreateObjectSet<cartelera>("cartelera");
                }
                return _cartelera;
            }
        }
        private ObjectSet<cartelera> _cartelera;
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<categorias> categorias
        {
            get
            {
                if ((_categorias == null))
                {
                    _categorias = base.CreateObjectSet<categorias>("categorias");
                }
                return _categorias;
            }
        }
        private ObjectSet<categorias> _categorias;
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<cines> cines
        {
            get
            {
                if ((_cines == null))
                {
                    _cines = base.CreateObjectSet<cines>("cines");
                }
                return _cines;
            }
        }
        private ObjectSet<cines> _cines;
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<comunas> comunas
        {
            get
            {
                if ((_comunas == null))
                {
                    _comunas = base.CreateObjectSet<comunas>("comunas");
                }
                return _comunas;
            }
        }
        private ObjectSet<comunas> _comunas;
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<entrada> entrada
        {
            get
            {
                if ((_entrada == null))
                {
                    _entrada = base.CreateObjectSet<entrada>("entrada");
                }
                return _entrada;
            }
        }
        private ObjectSet<entrada> _entrada;
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<formatoPeliculas> formatoPeliculas
        {
            get
            {
                if ((_formatoPeliculas == null))
                {
                    _formatoPeliculas = base.CreateObjectSet<formatoPeliculas>("formatoPeliculas");
                }
                return _formatoPeliculas;
            }
        }
        private ObjectSet<formatoPeliculas> _formatoPeliculas;
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<funcion> funcion
        {
            get
            {
                if ((_funcion == null))
                {
                    _funcion = base.CreateObjectSet<funcion>("funcion");
                }
                return _funcion;
            }
        }
        private ObjectSet<funcion> _funcion;
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<peliculas> peliculas
        {
            get
            {
                if ((_peliculas == null))
                {
                    _peliculas = base.CreateObjectSet<peliculas>("peliculas");
                }
                return _peliculas;
            }
        }
        private ObjectSet<peliculas> _peliculas;
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<salas> salas
        {
            get
            {
                if ((_salas == null))
                {
                    _salas = base.CreateObjectSet<salas>("salas");
                }
                return _salas;
            }
        }
        private ObjectSet<salas> _salas;
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<tipoAsientos> tipoAsientos
        {
            get
            {
                if ((_tipoAsientos == null))
                {
                    _tipoAsientos = base.CreateObjectSet<tipoAsientos>("tipoAsientos");
                }
                return _tipoAsientos;
            }
        }
        private ObjectSet<tipoAsientos> _tipoAsientos;
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<usuarios> usuarios
        {
            get
            {
                if ((_usuarios == null))
                {
                    _usuarios = base.CreateObjectSet<usuarios>("usuarios");
                }
                return _usuarios;
            }
        }
        private ObjectSet<usuarios> _usuarios;

        #endregion

        #region Métodos AddTo
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet cartelera. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddTocartelera(cartelera cartelera)
        {
            base.AddObject("cartelera", cartelera);
        }
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet categorias. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddTocategorias(categorias categorias)
        {
            base.AddObject("categorias", categorias);
        }
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet cines. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddTocines(cines cines)
        {
            base.AddObject("cines", cines);
        }
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet comunas. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddTocomunas(comunas comunas)
        {
            base.AddObject("comunas", comunas);
        }
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet entrada. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddToentrada(entrada entrada)
        {
            base.AddObject("entrada", entrada);
        }
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet formatoPeliculas. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddToformatoPeliculas(formatoPeliculas formatoPeliculas)
        {
            base.AddObject("formatoPeliculas", formatoPeliculas);
        }
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet funcion. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddTofuncion(funcion funcion)
        {
            base.AddObject("funcion", funcion);
        }
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet peliculas. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddTopeliculas(peliculas peliculas)
        {
            base.AddObject("peliculas", peliculas);
        }
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet salas. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddTosalas(salas salas)
        {
            base.AddObject("salas", salas);
        }
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet tipoAsientos. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddTotipoAsientos(tipoAsientos tipoAsientos)
        {
            base.AddObject("tipoAsientos", tipoAsientos);
        }
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet usuarios. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddTousuarios(usuarios usuarios)
        {
            base.AddObject("usuarios", usuarios);
        }

        #endregion

    }

    #endregion

    #region Entidades
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="CineSalinasModel", Name="cartelera")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class cartelera : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto cartelera.
        /// </summary>
        /// <param name="id">Valor inicial de la propiedad id.</param>
        /// <param name="titulo">Valor inicial de la propiedad titulo.</param>
        /// <param name="sinopsis">Valor inicial de la propiedad sinopsis.</param>
        /// <param name="director">Valor inicial de la propiedad director.</param>
        /// <param name="reparto">Valor inicial de la propiedad reparto.</param>
        /// <param name="idCategoria">Valor inicial de la propiedad idCategoria.</param>
        /// <param name="imagen">Valor inicial de la propiedad imagen.</param>
        /// <param name="video">Valor inicial de la propiedad video.</param>
        /// <param name="estado">Valor inicial de la propiedad estado.</param>
        public static cartelera Createcartelera(global::System.Int32 id, global::System.String titulo, global::System.String sinopsis, global::System.String director, global::System.String reparto, global::System.Int32 idCategoria, global::System.String imagen, global::System.String video, global::System.String estado)
        {
            cartelera cartelera = new cartelera();
            cartelera.id = id;
            cartelera.titulo = titulo;
            cartelera.sinopsis = sinopsis;
            cartelera.director = director;
            cartelera.reparto = reparto;
            cartelera.idCategoria = idCategoria;
            cartelera.imagen = imagen;
            cartelera.video = video;
            cartelera.estado = estado;
            return cartelera;
        }

        #endregion

        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String titulo
        {
            get
            {
                return _titulo;
            }
            set
            {
                OntituloChanging(value);
                ReportPropertyChanging("titulo");
                _titulo = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("titulo");
                OntituloChanged();
            }
        }
        private global::System.String _titulo;
        partial void OntituloChanging(global::System.String value);
        partial void OntituloChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String sinopsis
        {
            get
            {
                return _sinopsis;
            }
            set
            {
                OnsinopsisChanging(value);
                ReportPropertyChanging("sinopsis");
                _sinopsis = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("sinopsis");
                OnsinopsisChanged();
            }
        }
        private global::System.String _sinopsis;
        partial void OnsinopsisChanging(global::System.String value);
        partial void OnsinopsisChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String director
        {
            get
            {
                return _director;
            }
            set
            {
                OndirectorChanging(value);
                ReportPropertyChanging("director");
                _director = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("director");
                OndirectorChanged();
            }
        }
        private global::System.String _director;
        partial void OndirectorChanging(global::System.String value);
        partial void OndirectorChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String reparto
        {
            get
            {
                return _reparto;
            }
            set
            {
                OnrepartoChanging(value);
                ReportPropertyChanging("reparto");
                _reparto = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("reparto");
                OnrepartoChanged();
            }
        }
        private global::System.String _reparto;
        partial void OnrepartoChanging(global::System.String value);
        partial void OnrepartoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 idCategoria
        {
            get
            {
                return _idCategoria;
            }
            set
            {
                OnidCategoriaChanging(value);
                ReportPropertyChanging("idCategoria");
                _idCategoria = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("idCategoria");
                OnidCategoriaChanged();
            }
        }
        private global::System.Int32 _idCategoria;
        partial void OnidCategoriaChanging(global::System.Int32 value);
        partial void OnidCategoriaChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String imagen
        {
            get
            {
                return _imagen;
            }
            set
            {
                OnimagenChanging(value);
                ReportPropertyChanging("imagen");
                _imagen = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("imagen");
                OnimagenChanged();
            }
        }
        private global::System.String _imagen;
        partial void OnimagenChanging(global::System.String value);
        partial void OnimagenChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String video
        {
            get
            {
                return _video;
            }
            set
            {
                OnvideoChanging(value);
                ReportPropertyChanging("video");
                _video = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("video");
                OnvideoChanged();
            }
        }
        private global::System.String _video;
        partial void OnvideoChanging(global::System.String value);
        partial void OnvideoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String estado
        {
            get
            {
                return _estado;
            }
            set
            {
                OnestadoChanging(value);
                ReportPropertyChanging("estado");
                _estado = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("estado");
                OnestadoChanged();
            }
        }
        private global::System.String _estado;
        partial void OnestadoChanging(global::System.String value);
        partial void OnestadoChanged();

        #endregion

    
        #region Propiedades de navegación
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("CineSalinasModel", "FK__cartelera__idCat__1CF15040", "categorias")]
        public categorias categorias
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<categorias>("CineSalinasModel.FK__cartelera__idCat__1CF15040", "categorias").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<categorias>("CineSalinasModel.FK__cartelera__idCat__1CF15040", "categorias").Value = value;
            }
        }
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<categorias> categoriasReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<categorias>("CineSalinasModel.FK__cartelera__idCat__1CF15040", "categorias");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<categorias>("CineSalinasModel.FK__cartelera__idCat__1CF15040", "categorias", value);
                }
            }
        }
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("CineSalinasModel", "FK__peliculas__idCar__21B6055D", "peliculas")]
        public EntityCollection<peliculas> peliculas
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<peliculas>("CineSalinasModel.FK__peliculas__idCar__21B6055D", "peliculas");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<peliculas>("CineSalinasModel.FK__peliculas__idCar__21B6055D", "peliculas", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="CineSalinasModel", Name="categorias")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class categorias : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto categorias.
        /// </summary>
        /// <param name="id">Valor inicial de la propiedad id.</param>
        /// <param name="categoria">Valor inicial de la propiedad categoria.</param>
        public static categorias Createcategorias(global::System.Int32 id, global::System.String categoria)
        {
            categorias categorias = new categorias();
            categorias.id = id;
            categorias.categoria = categoria;
            return categorias;
        }

        #endregion

        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String categoria
        {
            get
            {
                return _categoria;
            }
            set
            {
                OncategoriaChanging(value);
                ReportPropertyChanging("categoria");
                _categoria = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("categoria");
                OncategoriaChanged();
            }
        }
        private global::System.String _categoria;
        partial void OncategoriaChanging(global::System.String value);
        partial void OncategoriaChanged();

        #endregion

    
        #region Propiedades de navegación
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("CineSalinasModel", "FK__cartelera__idCat__1CF15040", "cartelera")]
        public EntityCollection<cartelera> cartelera
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<cartelera>("CineSalinasModel.FK__cartelera__idCat__1CF15040", "cartelera");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<cartelera>("CineSalinasModel.FK__cartelera__idCat__1CF15040", "cartelera", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="CineSalinasModel", Name="cines")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class cines : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto cines.
        /// </summary>
        /// <param name="id">Valor inicial de la propiedad id.</param>
        /// <param name="nombre">Valor inicial de la propiedad nombre.</param>
        /// <param name="ubicación">Valor inicial de la propiedad ubicación.</param>
        /// <param name="idComuna">Valor inicial de la propiedad idComuna.</param>
        /// <param name="numero">Valor inicial de la propiedad numero.</param>
        /// <param name="mapa">Valor inicial de la propiedad mapa.</param>
        public static cines Createcines(global::System.Int32 id, global::System.String nombre, global::System.String ubicación, global::System.Int32 idComuna, global::System.Int32 numero, global::System.String mapa)
        {
            cines cines = new cines();
            cines.id = id;
            cines.nombre = nombre;
            cines.ubicación = ubicación;
            cines.idComuna = idComuna;
            cines.numero = numero;
            cines.mapa = mapa;
            return cines;
        }

        #endregion

        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String nombre
        {
            get
            {
                return _nombre;
            }
            set
            {
                OnnombreChanging(value);
                ReportPropertyChanging("nombre");
                _nombre = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("nombre");
                OnnombreChanged();
            }
        }
        private global::System.String _nombre;
        partial void OnnombreChanging(global::System.String value);
        partial void OnnombreChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ubicación
        {
            get
            {
                return _ubicación;
            }
            set
            {
                OnubicaciónChanging(value);
                ReportPropertyChanging("ubicación");
                _ubicación = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("ubicación");
                OnubicaciónChanged();
            }
        }
        private global::System.String _ubicación;
        partial void OnubicaciónChanging(global::System.String value);
        partial void OnubicaciónChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 idComuna
        {
            get
            {
                return _idComuna;
            }
            set
            {
                OnidComunaChanging(value);
                ReportPropertyChanging("idComuna");
                _idComuna = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("idComuna");
                OnidComunaChanged();
            }
        }
        private global::System.Int32 _idComuna;
        partial void OnidComunaChanging(global::System.Int32 value);
        partial void OnidComunaChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 numero
        {
            get
            {
                return _numero;
            }
            set
            {
                OnnumeroChanging(value);
                ReportPropertyChanging("numero");
                _numero = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("numero");
                OnnumeroChanged();
            }
        }
        private global::System.Int32 _numero;
        partial void OnnumeroChanging(global::System.Int32 value);
        partial void OnnumeroChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String mapa
        {
            get
            {
                return _mapa;
            }
            set
            {
                OnmapaChanging(value);
                ReportPropertyChanging("mapa");
                _mapa = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("mapa");
                OnmapaChanged();
            }
        }
        private global::System.String _mapa;
        partial void OnmapaChanging(global::System.String value);
        partial void OnmapaChanged();

        #endregion

    
        #region Propiedades de navegación
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("CineSalinasModel", "FK__cines__idComuna__145C0A3F", "comunas")]
        public comunas comunas
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<comunas>("CineSalinasModel.FK__cines__idComuna__145C0A3F", "comunas").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<comunas>("CineSalinasModel.FK__cines__idComuna__145C0A3F", "comunas").Value = value;
            }
        }
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<comunas> comunasReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<comunas>("CineSalinasModel.FK__cines__idComuna__145C0A3F", "comunas");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<comunas>("CineSalinasModel.FK__cines__idComuna__145C0A3F", "comunas", value);
                }
            }
        }
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("CineSalinasModel", "FK__funcion__idCine__286302EC", "funcion")]
        public EntityCollection<funcion> funcion
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<funcion>("CineSalinasModel.FK__funcion__idCine__286302EC", "funcion");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<funcion>("CineSalinasModel.FK__funcion__idCine__286302EC", "funcion", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="CineSalinasModel", Name="comunas")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class comunas : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto comunas.
        /// </summary>
        /// <param name="id">Valor inicial de la propiedad id.</param>
        /// <param name="comuna">Valor inicial de la propiedad comuna.</param>
        public static comunas Createcomunas(global::System.Int32 id, global::System.String comuna)
        {
            comunas comunas = new comunas();
            comunas.id = id;
            comunas.comuna = comuna;
            return comunas;
        }

        #endregion

        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String comuna
        {
            get
            {
                return _comuna;
            }
            set
            {
                OncomunaChanging(value);
                ReportPropertyChanging("comuna");
                _comuna = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("comuna");
                OncomunaChanged();
            }
        }
        private global::System.String _comuna;
        partial void OncomunaChanging(global::System.String value);
        partial void OncomunaChanged();

        #endregion

    
        #region Propiedades de navegación
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("CineSalinasModel", "FK__cines__idComuna__145C0A3F", "cines")]
        public EntityCollection<cines> cines
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<cines>("CineSalinasModel.FK__cines__idComuna__145C0A3F", "cines");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<cines>("CineSalinasModel.FK__cines__idComuna__145C0A3F", "cines", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="CineSalinasModel", Name="entrada")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class entrada : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto entrada.
        /// </summary>
        /// <param name="id">Valor inicial de la propiedad id.</param>
        public static entrada Createentrada(global::System.Int32 id)
        {
            entrada entrada = new entrada();
            entrada.id = id;
            return entrada;
        }

        #endregion

        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String usuario
        {
            get
            {
                return _usuario;
            }
            set
            {
                OnusuarioChanging(value);
                ReportPropertyChanging("usuario");
                _usuario = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("usuario");
                OnusuarioChanged();
            }
        }
        private global::System.String _usuario;
        partial void OnusuarioChanging(global::System.String value);
        partial void OnusuarioChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> idFuncion
        {
            get
            {
                return _idFuncion;
            }
            set
            {
                OnidFuncionChanging(value);
                ReportPropertyChanging("idFuncion");
                _idFuncion = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("idFuncion");
                OnidFuncionChanged();
            }
        }
        private Nullable<global::System.Int32> _idFuncion;
        partial void OnidFuncionChanging(Nullable<global::System.Int32> value);
        partial void OnidFuncionChanged();

        #endregion

    
        #region Propiedades de navegación
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("CineSalinasModel", "FK__entrada__idFunci__2C3393D0", "funcion")]
        public funcion funcion
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<funcion>("CineSalinasModel.FK__entrada__idFunci__2C3393D0", "funcion").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<funcion>("CineSalinasModel.FK__entrada__idFunci__2C3393D0", "funcion").Value = value;
            }
        }
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<funcion> funcionReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<funcion>("CineSalinasModel.FK__entrada__idFunci__2C3393D0", "funcion");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<funcion>("CineSalinasModel.FK__entrada__idFunci__2C3393D0", "funcion", value);
                }
            }
        }
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("CineSalinasModel", "FK__entrada__usuario__2B3F6F97", "usuarios")]
        public usuarios usuarios
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<usuarios>("CineSalinasModel.FK__entrada__usuario__2B3F6F97", "usuarios").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<usuarios>("CineSalinasModel.FK__entrada__usuario__2B3F6F97", "usuarios").Value = value;
            }
        }
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<usuarios> usuariosReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<usuarios>("CineSalinasModel.FK__entrada__usuario__2B3F6F97", "usuarios");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<usuarios>("CineSalinasModel.FK__entrada__usuario__2B3F6F97", "usuarios", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="CineSalinasModel", Name="formatoPeliculas")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class formatoPeliculas : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto formatoPeliculas.
        /// </summary>
        /// <param name="id">Valor inicial de la propiedad id.</param>
        /// <param name="formato">Valor inicial de la propiedad formato.</param>
        /// <param name="precio">Valor inicial de la propiedad precio.</param>
        /// <param name="descripcion">Valor inicial de la propiedad descripcion.</param>
        /// <param name="imagen">Valor inicial de la propiedad imagen.</param>
        public static formatoPeliculas CreateformatoPeliculas(global::System.Int32 id, global::System.String formato, global::System.Int32 precio, global::System.String descripcion, global::System.String imagen)
        {
            formatoPeliculas formatoPeliculas = new formatoPeliculas();
            formatoPeliculas.id = id;
            formatoPeliculas.formato = formato;
            formatoPeliculas.precio = precio;
            formatoPeliculas.descripcion = descripcion;
            formatoPeliculas.imagen = imagen;
            return formatoPeliculas;
        }

        #endregion

        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String formato
        {
            get
            {
                return _formato;
            }
            set
            {
                OnformatoChanging(value);
                ReportPropertyChanging("formato");
                _formato = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("formato");
                OnformatoChanged();
            }
        }
        private global::System.String _formato;
        partial void OnformatoChanging(global::System.String value);
        partial void OnformatoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 precio
        {
            get
            {
                return _precio;
            }
            set
            {
                OnprecioChanging(value);
                ReportPropertyChanging("precio");
                _precio = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("precio");
                OnprecioChanged();
            }
        }
        private global::System.Int32 _precio;
        partial void OnprecioChanging(global::System.Int32 value);
        partial void OnprecioChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String descripcion
        {
            get
            {
                return _descripcion;
            }
            set
            {
                OndescripcionChanging(value);
                ReportPropertyChanging("descripcion");
                _descripcion = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("descripcion");
                OndescripcionChanged();
            }
        }
        private global::System.String _descripcion;
        partial void OndescripcionChanging(global::System.String value);
        partial void OndescripcionChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String imagen
        {
            get
            {
                return _imagen;
            }
            set
            {
                OnimagenChanging(value);
                ReportPropertyChanging("imagen");
                _imagen = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("imagen");
                OnimagenChanged();
            }
        }
        private global::System.String _imagen;
        partial void OnimagenChanging(global::System.String value);
        partial void OnimagenChanged();

        #endregion

    
        #region Propiedades de navegación
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("CineSalinasModel", "FK__peliculas__idFor__22AA2996", "peliculas")]
        public EntityCollection<peliculas> peliculas
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<peliculas>("CineSalinasModel.FK__peliculas__idFor__22AA2996", "peliculas");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<peliculas>("CineSalinasModel.FK__peliculas__idFor__22AA2996", "peliculas", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="CineSalinasModel", Name="funcion")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class funcion : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto funcion.
        /// </summary>
        /// <param name="id">Valor inicial de la propiedad id.</param>
        /// <param name="idSala">Valor inicial de la propiedad idSala.</param>
        /// <param name="idTipoAsiento">Valor inicial de la propiedad idTipoAsiento.</param>
        /// <param name="numeroAsiento">Valor inicial de la propiedad numeroAsiento.</param>
        /// <param name="idPelicula">Valor inicial de la propiedad idPelicula.</param>
        /// <param name="hora">Valor inicial de la propiedad hora.</param>
        /// <param name="fecha">Valor inicial de la propiedad fecha.</param>
        /// <param name="precio">Valor inicial de la propiedad precio.</param>
        /// <param name="estado">Valor inicial de la propiedad estado.</param>
        public static funcion Createfuncion(global::System.Int32 id, global::System.Int32 idSala, global::System.Int32 idTipoAsiento, global::System.Int32 numeroAsiento, global::System.Int32 idPelicula, global::System.String hora, global::System.String fecha, global::System.Int32 precio, global::System.Int32 estado)
        {
            funcion funcion = new funcion();
            funcion.id = id;
            funcion.idSala = idSala;
            funcion.idTipoAsiento = idTipoAsiento;
            funcion.numeroAsiento = numeroAsiento;
            funcion.idPelicula = idPelicula;
            funcion.hora = hora;
            funcion.fecha = fecha;
            funcion.precio = precio;
            funcion.estado = estado;
            return funcion;
        }

        #endregion

        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 idSala
        {
            get
            {
                return _idSala;
            }
            set
            {
                OnidSalaChanging(value);
                ReportPropertyChanging("idSala");
                _idSala = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("idSala");
                OnidSalaChanged();
            }
        }
        private global::System.Int32 _idSala;
        partial void OnidSalaChanging(global::System.Int32 value);
        partial void OnidSalaChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 idTipoAsiento
        {
            get
            {
                return _idTipoAsiento;
            }
            set
            {
                OnidTipoAsientoChanging(value);
                ReportPropertyChanging("idTipoAsiento");
                _idTipoAsiento = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("idTipoAsiento");
                OnidTipoAsientoChanged();
            }
        }
        private global::System.Int32 _idTipoAsiento;
        partial void OnidTipoAsientoChanging(global::System.Int32 value);
        partial void OnidTipoAsientoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 numeroAsiento
        {
            get
            {
                return _numeroAsiento;
            }
            set
            {
                OnnumeroAsientoChanging(value);
                ReportPropertyChanging("numeroAsiento");
                _numeroAsiento = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("numeroAsiento");
                OnnumeroAsientoChanged();
            }
        }
        private global::System.Int32 _numeroAsiento;
        partial void OnnumeroAsientoChanging(global::System.Int32 value);
        partial void OnnumeroAsientoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 idPelicula
        {
            get
            {
                return _idPelicula;
            }
            set
            {
                OnidPeliculaChanging(value);
                ReportPropertyChanging("idPelicula");
                _idPelicula = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("idPelicula");
                OnidPeliculaChanged();
            }
        }
        private global::System.Int32 _idPelicula;
        partial void OnidPeliculaChanging(global::System.Int32 value);
        partial void OnidPeliculaChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> idCine
        {
            get
            {
                return _idCine;
            }
            set
            {
                OnidCineChanging(value);
                ReportPropertyChanging("idCine");
                _idCine = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("idCine");
                OnidCineChanged();
            }
        }
        private Nullable<global::System.Int32> _idCine;
        partial void OnidCineChanging(Nullable<global::System.Int32> value);
        partial void OnidCineChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String hora
        {
            get
            {
                return _hora;
            }
            set
            {
                OnhoraChanging(value);
                ReportPropertyChanging("hora");
                _hora = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("hora");
                OnhoraChanged();
            }
        }
        private global::System.String _hora;
        partial void OnhoraChanging(global::System.String value);
        partial void OnhoraChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String fecha
        {
            get
            {
                return _fecha;
            }
            set
            {
                OnfechaChanging(value);
                ReportPropertyChanging("fecha");
                _fecha = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("fecha");
                OnfechaChanged();
            }
        }
        private global::System.String _fecha;
        partial void OnfechaChanging(global::System.String value);
        partial void OnfechaChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 precio
        {
            get
            {
                return _precio;
            }
            set
            {
                OnprecioChanging(value);
                ReportPropertyChanging("precio");
                _precio = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("precio");
                OnprecioChanged();
            }
        }
        private global::System.Int32 _precio;
        partial void OnprecioChanging(global::System.Int32 value);
        partial void OnprecioChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 estado
        {
            get
            {
                return _estado;
            }
            set
            {
                OnestadoChanging(value);
                ReportPropertyChanging("estado");
                _estado = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("estado");
                OnestadoChanged();
            }
        }
        private global::System.Int32 _estado;
        partial void OnestadoChanging(global::System.Int32 value);
        partial void OnestadoChanged();

        #endregion

    
        #region Propiedades de navegación
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("CineSalinasModel", "FK__funcion__idCine__286302EC", "cines")]
        public cines cines
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<cines>("CineSalinasModel.FK__funcion__idCine__286302EC", "cines").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<cines>("CineSalinasModel.FK__funcion__idCine__286302EC", "cines").Value = value;
            }
        }
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<cines> cinesReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<cines>("CineSalinasModel.FK__funcion__idCine__286302EC", "cines");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<cines>("CineSalinasModel.FK__funcion__idCine__286302EC", "cines", value);
                }
            }
        }
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("CineSalinasModel", "FK__entrada__idFunci__2C3393D0", "entrada")]
        public EntityCollection<entrada> entrada
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<entrada>("CineSalinasModel.FK__entrada__idFunci__2C3393D0", "entrada");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<entrada>("CineSalinasModel.FK__entrada__idFunci__2C3393D0", "entrada", value);
                }
            }
        }
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("CineSalinasModel", "FK__funcion__idPelic__276EDEB3", "peliculas")]
        public peliculas peliculas
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<peliculas>("CineSalinasModel.FK__funcion__idPelic__276EDEB3", "peliculas").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<peliculas>("CineSalinasModel.FK__funcion__idPelic__276EDEB3", "peliculas").Value = value;
            }
        }
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<peliculas> peliculasReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<peliculas>("CineSalinasModel.FK__funcion__idPelic__276EDEB3", "peliculas");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<peliculas>("CineSalinasModel.FK__funcion__idPelic__276EDEB3", "peliculas", value);
                }
            }
        }
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("CineSalinasModel", "FK__funcion__idSala__25869641", "salas")]
        public salas salas
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<salas>("CineSalinasModel.FK__funcion__idSala__25869641", "salas").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<salas>("CineSalinasModel.FK__funcion__idSala__25869641", "salas").Value = value;
            }
        }
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<salas> salasReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<salas>("CineSalinasModel.FK__funcion__idSala__25869641", "salas");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<salas>("CineSalinasModel.FK__funcion__idSala__25869641", "salas", value);
                }
            }
        }
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("CineSalinasModel", "FK__funcion__idTipoA__267ABA7A", "tipoAsientos")]
        public tipoAsientos tipoAsientos
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tipoAsientos>("CineSalinasModel.FK__funcion__idTipoA__267ABA7A", "tipoAsientos").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tipoAsientos>("CineSalinasModel.FK__funcion__idTipoA__267ABA7A", "tipoAsientos").Value = value;
            }
        }
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<tipoAsientos> tipoAsientosReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tipoAsientos>("CineSalinasModel.FK__funcion__idTipoA__267ABA7A", "tipoAsientos");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<tipoAsientos>("CineSalinasModel.FK__funcion__idTipoA__267ABA7A", "tipoAsientos", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="CineSalinasModel", Name="peliculas")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class peliculas : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto peliculas.
        /// </summary>
        /// <param name="id">Valor inicial de la propiedad id.</param>
        /// <param name="idCartelera">Valor inicial de la propiedad idCartelera.</param>
        /// <param name="idFormato">Valor inicial de la propiedad idFormato.</param>
        public static peliculas Createpeliculas(global::System.Int32 id, global::System.Int32 idCartelera, global::System.Int32 idFormato)
        {
            peliculas peliculas = new peliculas();
            peliculas.id = id;
            peliculas.idCartelera = idCartelera;
            peliculas.idFormato = idFormato;
            return peliculas;
        }

        #endregion

        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 idCartelera
        {
            get
            {
                return _idCartelera;
            }
            set
            {
                OnidCarteleraChanging(value);
                ReportPropertyChanging("idCartelera");
                _idCartelera = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("idCartelera");
                OnidCarteleraChanged();
            }
        }
        private global::System.Int32 _idCartelera;
        partial void OnidCarteleraChanging(global::System.Int32 value);
        partial void OnidCarteleraChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 idFormato
        {
            get
            {
                return _idFormato;
            }
            set
            {
                OnidFormatoChanging(value);
                ReportPropertyChanging("idFormato");
                _idFormato = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("idFormato");
                OnidFormatoChanged();
            }
        }
        private global::System.Int32 _idFormato;
        partial void OnidFormatoChanging(global::System.Int32 value);
        partial void OnidFormatoChanged();

        #endregion

    
        #region Propiedades de navegación
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("CineSalinasModel", "FK__peliculas__idCar__21B6055D", "cartelera")]
        public cartelera cartelera
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<cartelera>("CineSalinasModel.FK__peliculas__idCar__21B6055D", "cartelera").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<cartelera>("CineSalinasModel.FK__peliculas__idCar__21B6055D", "cartelera").Value = value;
            }
        }
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<cartelera> carteleraReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<cartelera>("CineSalinasModel.FK__peliculas__idCar__21B6055D", "cartelera");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<cartelera>("CineSalinasModel.FK__peliculas__idCar__21B6055D", "cartelera", value);
                }
            }
        }
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("CineSalinasModel", "FK__peliculas__idFor__22AA2996", "formatoPeliculas")]
        public formatoPeliculas formatoPeliculas
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<formatoPeliculas>("CineSalinasModel.FK__peliculas__idFor__22AA2996", "formatoPeliculas").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<formatoPeliculas>("CineSalinasModel.FK__peliculas__idFor__22AA2996", "formatoPeliculas").Value = value;
            }
        }
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<formatoPeliculas> formatoPeliculasReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<formatoPeliculas>("CineSalinasModel.FK__peliculas__idFor__22AA2996", "formatoPeliculas");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<formatoPeliculas>("CineSalinasModel.FK__peliculas__idFor__22AA2996", "formatoPeliculas", value);
                }
            }
        }
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("CineSalinasModel", "FK__funcion__idPelic__276EDEB3", "funcion")]
        public EntityCollection<funcion> funcion
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<funcion>("CineSalinasModel.FK__funcion__idPelic__276EDEB3", "funcion");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<funcion>("CineSalinasModel.FK__funcion__idPelic__276EDEB3", "funcion", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="CineSalinasModel", Name="salas")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class salas : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto salas.
        /// </summary>
        /// <param name="id">Valor inicial de la propiedad id.</param>
        /// <param name="numero">Valor inicial de la propiedad numero.</param>
        /// <param name="cantidadAsientos">Valor inicial de la propiedad cantidadAsientos.</param>
        public static salas Createsalas(global::System.Int32 id, global::System.Int32 numero, global::System.Int32 cantidadAsientos)
        {
            salas salas = new salas();
            salas.id = id;
            salas.numero = numero;
            salas.cantidadAsientos = cantidadAsientos;
            return salas;
        }

        #endregion

        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 numero
        {
            get
            {
                return _numero;
            }
            set
            {
                OnnumeroChanging(value);
                ReportPropertyChanging("numero");
                _numero = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("numero");
                OnnumeroChanged();
            }
        }
        private global::System.Int32 _numero;
        partial void OnnumeroChanging(global::System.Int32 value);
        partial void OnnumeroChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 cantidadAsientos
        {
            get
            {
                return _cantidadAsientos;
            }
            set
            {
                OncantidadAsientosChanging(value);
                ReportPropertyChanging("cantidadAsientos");
                _cantidadAsientos = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("cantidadAsientos");
                OncantidadAsientosChanged();
            }
        }
        private global::System.Int32 _cantidadAsientos;
        partial void OncantidadAsientosChanging(global::System.Int32 value);
        partial void OncantidadAsientosChanged();

        #endregion

    
        #region Propiedades de navegación
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("CineSalinasModel", "FK__funcion__idSala__25869641", "funcion")]
        public EntityCollection<funcion> funcion
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<funcion>("CineSalinasModel.FK__funcion__idSala__25869641", "funcion");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<funcion>("CineSalinasModel.FK__funcion__idSala__25869641", "funcion", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="CineSalinasModel", Name="tipoAsientos")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class tipoAsientos : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto tipoAsientos.
        /// </summary>
        /// <param name="id">Valor inicial de la propiedad id.</param>
        /// <param name="tipo">Valor inicial de la propiedad tipo.</param>
        /// <param name="precio">Valor inicial de la propiedad precio.</param>
        /// <param name="descripcion">Valor inicial de la propiedad descripcion.</param>
        /// <param name="imagen">Valor inicial de la propiedad imagen.</param>
        public static tipoAsientos CreatetipoAsientos(global::System.Int32 id, global::System.String tipo, global::System.Int32 precio, global::System.String descripcion, global::System.String imagen)
        {
            tipoAsientos tipoAsientos = new tipoAsientos();
            tipoAsientos.id = id;
            tipoAsientos.tipo = tipo;
            tipoAsientos.precio = precio;
            tipoAsientos.descripcion = descripcion;
            tipoAsientos.imagen = imagen;
            return tipoAsientos;
        }

        #endregion

        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String tipo
        {
            get
            {
                return _tipo;
            }
            set
            {
                OntipoChanging(value);
                ReportPropertyChanging("tipo");
                _tipo = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("tipo");
                OntipoChanged();
            }
        }
        private global::System.String _tipo;
        partial void OntipoChanging(global::System.String value);
        partial void OntipoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 precio
        {
            get
            {
                return _precio;
            }
            set
            {
                OnprecioChanging(value);
                ReportPropertyChanging("precio");
                _precio = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("precio");
                OnprecioChanged();
            }
        }
        private global::System.Int32 _precio;
        partial void OnprecioChanging(global::System.Int32 value);
        partial void OnprecioChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String descripcion
        {
            get
            {
                return _descripcion;
            }
            set
            {
                OndescripcionChanging(value);
                ReportPropertyChanging("descripcion");
                _descripcion = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("descripcion");
                OndescripcionChanged();
            }
        }
        private global::System.String _descripcion;
        partial void OndescripcionChanging(global::System.String value);
        partial void OndescripcionChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String imagen
        {
            get
            {
                return _imagen;
            }
            set
            {
                OnimagenChanging(value);
                ReportPropertyChanging("imagen");
                _imagen = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("imagen");
                OnimagenChanged();
            }
        }
        private global::System.String _imagen;
        partial void OnimagenChanging(global::System.String value);
        partial void OnimagenChanged();

        #endregion

    
        #region Propiedades de navegación
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("CineSalinasModel", "FK__funcion__idTipoA__267ABA7A", "funcion")]
        public EntityCollection<funcion> funcion
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<funcion>("CineSalinasModel.FK__funcion__idTipoA__267ABA7A", "funcion");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<funcion>("CineSalinasModel.FK__funcion__idTipoA__267ABA7A", "funcion", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="CineSalinasModel", Name="usuarios")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class usuarios : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto usuarios.
        /// </summary>
        /// <param name="correo">Valor inicial de la propiedad correo.</param>
        /// <param name="clave">Valor inicial de la propiedad clave.</param>
        /// <param name="nombre">Valor inicial de la propiedad nombre.</param>
        /// <param name="apellido">Valor inicial de la propiedad apellido.</param>
        /// <param name="tipo">Valor inicial de la propiedad tipo.</param>
        public static usuarios Createusuarios(global::System.String correo, global::System.String clave, global::System.String nombre, global::System.String apellido, global::System.String tipo)
        {
            usuarios usuarios = new usuarios();
            usuarios.correo = correo;
            usuarios.clave = clave;
            usuarios.nombre = nombre;
            usuarios.apellido = apellido;
            usuarios.tipo = tipo;
            return usuarios;
        }

        #endregion

        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String correo
        {
            get
            {
                return _correo;
            }
            set
            {
                if (_correo != value)
                {
                    OncorreoChanging(value);
                    ReportPropertyChanging("correo");
                    _correo = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("correo");
                    OncorreoChanged();
                }
            }
        }
        private global::System.String _correo;
        partial void OncorreoChanging(global::System.String value);
        partial void OncorreoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String clave
        {
            get
            {
                return _clave;
            }
            set
            {
                OnclaveChanging(value);
                ReportPropertyChanging("clave");
                _clave = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("clave");
                OnclaveChanged();
            }
        }
        private global::System.String _clave;
        partial void OnclaveChanging(global::System.String value);
        partial void OnclaveChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String nombre
        {
            get
            {
                return _nombre;
            }
            set
            {
                OnnombreChanging(value);
                ReportPropertyChanging("nombre");
                _nombre = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("nombre");
                OnnombreChanged();
            }
        }
        private global::System.String _nombre;
        partial void OnnombreChanging(global::System.String value);
        partial void OnnombreChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String apellido
        {
            get
            {
                return _apellido;
            }
            set
            {
                OnapellidoChanging(value);
                ReportPropertyChanging("apellido");
                _apellido = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("apellido");
                OnapellidoChanged();
            }
        }
        private global::System.String _apellido;
        partial void OnapellidoChanging(global::System.String value);
        partial void OnapellidoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String tipo
        {
            get
            {
                return _tipo;
            }
            set
            {
                OntipoChanging(value);
                ReportPropertyChanging("tipo");
                _tipo = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("tipo");
                OntipoChanged();
            }
        }
        private global::System.String _tipo;
        partial void OntipoChanging(global::System.String value);
        partial void OntipoChanged();

        #endregion

    
        #region Propiedades de navegación
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("CineSalinasModel", "FK__entrada__usuario__2B3F6F97", "entrada")]
        public EntityCollection<entrada> entrada
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<entrada>("CineSalinasModel.FK__entrada__usuario__2B3F6F97", "entrada");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<entrada>("CineSalinasModel.FK__entrada__usuario__2B3F6F97", "entrada", value);
                }
            }
        }

        #endregion

    }

    #endregion

    
}
